REMEDIATION_TEMPLATES = {
    # --- Infrastructure & Docker ---
    "dockerfile.security.missing-user-entrypoint.missing-user-entrypoint": "CRITICAL: The container is configured to run as ROOT. Add a 'USER' instruction to your Dockerfile to mitigate privilege escalation risks.",
    "dockerfile.security.root_user": "HIGH: Container running as root. Implement 'USER nonroot' to follow the principle of least privilege.",
    "dockerfile.security.exposed-ssh-port": "CRITICAL: SSH port (22) is exposed in Dockerfile. Remove EXPOSE 22 and use 'docker exec' for container access.",
    # --- Secret Detection (Gitleaks & Custom) ---
    "GitleaksDetector": "CRITICAL: Hardcoded credentials found. 1. Revoke the secret immediately. 2. Rotate all affected keys. 3. Use Environment Variables or a Secret Manager.",
    "aws-access-token": "CRITICAL: AWS Access Key detected. Deactivate the key in IAM console and move it to AWS Secrets Manager.",
    "generic-api-key": "HIGH: API Key found in source code. This can lead to unauthorized service access. Use .env files (excluded from Git).",
    # --- Dependency Scanning ---
    "DEP_VULN_PYPI": "HIGH: Vulnerable Python package detected. Review the specific CVE and run 'pip install --upgrade <package_name>' to install the patched version.",
    "DEP_VULN_NPM": "HIGH: Vulnerable Node.js dependency. Run 'npm audit fix' or update the package manually in package.json.",
    # --- Static Analysis (SAST) ---
    # Note: rule_id values here must match detector output exactly — never raw CWE codes
    "SAST_SQL_INJECTION": "CRITICAL: SQL Injection vulnerability. Use parameterized queries or a secure ORM (SQLAlchemy, Django ORM) instead of string formatting.",
    "SAST_SQL_INJECTION_AST": "CRITICAL: Confirmed SQL Injection via taint analysis. Tainted variable flows into execute(). Switch to parameterized queries immediately.",
    "SAST_XSS": "MEDIUM: Cross-Site Scripting (XSS). Sanitize and escape all user input before rendering in the browser.",
    "hardcoded_password_string": "HIGH: Hardcoded password detected. Remove the plaintext string and use an encrypted configuration provider.",
    "try_except_pass": "LOW: Silent exception handling. Refactor code to log errors properly instead of using 'pass' in except blocks.",
    # --- CI/CD & GitHub Actions ---
    "GHA_UNPINNED_ACTION": "MEDIUM: GitHub Action is not pinned to a specific SHA. Use a full commit hash instead of a tag (e.g., @v4) to prevent supply chain attacks.",
    # Note: GHA_MISSING_TIMEOUT removed — rule_id not generated by any active detector
    # --- Defaults ---
    "general_advice": "ADVICE: Review the associated CWE/Rule documentation and apply security best practices for this specific language or framework.",
}